(function(){
 'use strict';
 if(window.parent!==window)return;
 const css=document.createElement('style');css.textContent='.kb-quick{border:1px solid #dbe3ea;border-radius:12px;background:white;padding:18px;margin:20px 0}.kb-quick h3{margin:0 0 12px}.kb-quick button{padding:12px;border:1px solid #ccd8e3;border-radius:8px;background:#f4f7fa;color:#17324d;cursor:pointer;text-align:left;font:inherit}.kb-quick-list{display:flex;flex-wrap:wrap;gap:10px;margin-top:12px}.kb-quick-list button{flex:1 1 210px}.kb-quick small{display:block;margin-top:5px;color:#526779}.kb-search{display:block;width:100%;padding:12px;margin:12px 0;border:1px solid #ccd8e3;border-radius:8px;font:inherit}.kb-home{display:inline-flex;align-items:center;min-height:44px;padding:8px 12px;color:#17324d;background:#f1f5f9;border-radius:8px;text-decoration:none}.kb-save-inline{position:sticky!important;top:0;bottom:auto!important;left:auto!important;max-width:none!important;margin:10px 0!important;z-index:90!important}@media print{.kb-quick,.kb-home,.kb-save-inline{display:none!important}}';document.head.append(css);
 for(const a of document.querySelectorAll('a[href="anbudskalkulator.html"],a[href="/anbudskalkulator.html"]'))if(a.textContent.trim()==='Anbudskalkulator')a.textContent='Mine verktøy';
 if(!document.querySelector('nav a[href="anbudskalkulator.html"],nav a[href="/anbudskalkulator.html"]')&&KBAuth.can('projects')&&!document.querySelector('a[href="/anbudskalkulator.html"]')){const home=document.createElement('a');home.href='/anbudskalkulator.html';home.className='kb-home';home.textContent='← Mine verktøy';document.querySelector('main')?.prepend(home);}
 const title=document.getElementById('hovedmenyTittel');
 if(KBAuth.can('projects')){
  let checked=0;
  async function remind(){if(document.visibilityState!=='visible'||Date.now()-checked<300000)return;const parts=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Oslo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date()),part=k=>parts.find(p=>p.type===k)?.value;if(Number(part('hour'))<16)return;checked=Date.now();try{const day=part('year')+'-'+part('month')+'-'+part('day');const {data,error}=await KBDatabase.getClient().rpc('kb_time_day',{p_day:day});if(error||!Array.isArray(data))return;let box=document.getElementById('kb-time-reminder');if(data.some(r=>!r.reviewed_at)){if(!box){box=document.createElement('aside');box.id='kb-time-reminder';box.className='kb-quick';box.setAttribute('role','status');const text=document.createElement('p');text.textContent='Ferdig for dagen? Se over prosjektene og timene dine. Du kan rette dem før du godkjenner utkastet.';const link=document.createElement('a');link.href='/timer.html#day-review';link.className='kb-home';link.textContent='Se over dagens timer →';box.append(text,link);(document.querySelector('main')||document.body).prepend(box);}}else box?.remove();}catch{}}
  remind();setInterval(remind,60000);document.addEventListener('visibilitychange',()=>{checked=0;remind();});
 }
 if(KBAuth.can('projects')&&(title||location.pathname==='/kalender.html')){
 const card=document.createElement('section');card.id='kb-time-home';card.setAttribute('aria-labelledby','kb-time-home-title');
 card.innerHTML='<div><p class="time-home-label">DIN ARBEIDSDAG</p><h2 id="kb-time-home-title">Før timene mens du jobber</h2><p>Velg prosjekt og start klokken. Henter du deler eller materialer til jobben, fortsetter timetelleren på samme kunde og prosjekt. Se over dagens timer før du godkjenner og sender dem til Tripletex.</p><p class="time-home-note">Du kontrollerer timene før sending</p></div><div class="time-home-actions"><a class="time-home-primary" href="/timer.html">⏱ Åpne timeføring →</a><a class="time-home-review" href="/timer.html#day-review">Se over dagens timer</a></div>';
 const style=document.createElement('style');style.textContent='#kb-time-home{display:flex;align-items:center;justify-content:space-between;gap:28px;padding:28px 32px;margin:16px 0 24px;border:1px solid #b9cddd;border-left:6px solid #e6ab32;border-radius:16px;background:#eaf2f8;color:#173750}#kb-time-home h2{font-size:clamp(24px,3vw,32px);line-height:1.2;margin:8px 0 12px;color:inherit}#kb-time-home p{max-width:650px;margin:8px 0;line-height:1.6}#kb-time-home .time-home-label{font-size:12px;letter-spacing:.1em;font-weight:750}#kb-time-home .time-home-note{font-size:13px;color:#466176}.time-home-actions{display:flex;flex-direction:column;gap:12px;flex-shrink:0}#kb-time-home .time-home-primary{display:block;padding:17px 24px;border-radius:10px;background:#173750;color:#fff;text-align:center;text-decoration:none;font-size:18px;font-weight:700;min-height:56px}#kb-time-home .time-home-review{display:block;padding:8px;text-align:center;color:inherit;min-height:44px}html[data-kb-theme=dark] #kb-time-home{background:#173149;border-color:#486581;border-left-color:#e6ab32;color:#eef6ff}html[data-kb-theme=dark] #kb-time-home .time-home-note{color:#c2d3e3}html[data-kb-theme=dark] #kb-time-home .time-home-primary{background:#f4c460!important;color:#172d40!important}@media(max-width:700px){#kb-time-home{display:block;padding:22px 20px}.time-home-actions{margin-top:18px}}@media print{#kb-time-home{display:none}}';document.head.append(style);
 if(title)document.getElementById('hovedmeny').prepend(card);else document.querySelector('main')?.prepend(card);
}
 if(title&&typeof lasteProsjekter==='function'){
   const section=document.createElement('section');section.className='kb-quick';section.innerHTML='<h3>Fortsett med et prosjekt</h3><button type="button">+ Nytt prosjekt</button><div class="kb-quick-list"></div>';
   title.before(section);const manage=document.createElement('button');manage.type='button';manage.textContent='Se alle prosjekter / slett';manage.style.marginLeft='10px';manage.onclick=()=>openProsjekter();section.querySelector('button').after(manage);section.querySelector('button').onclick=()=>{nyttProsjekt();render();};
   const list=section.querySelector('.kb-quick-list');
   function render(){list.replaceChildren();const projects=lasteProsjekter().slice().sort((a,b)=>String(b.sist_endret||b.dato).localeCompare(String(a.sist_endret||a.dato))).slice(0,4);if(!projects.length){const p=document.createElement('p');p.textContent='Ingen lagrede prosjekter ennå. Start med «Nytt prosjekt».';list.append(p);}for(const p of projects){const b=document.createElement('button');b.type='button';const name=document.createElement('strong');name.textContent=p.navn||'Uten navn';const meta=document.createElement('small');meta.textContent=[p.kunde,'Sist endret '+new Date(p.sist_endret||p.dato).toLocaleDateString('nb-NO')].filter(Boolean).join(' · ');b.append(name,meta);b.onclick=()=>{lastInnProsjekt(p.id);};list.append(b);}}
   render();const status=document.getElementById('kb-save-status');if(status){new MutationObserver(render).observe(status,{childList:true,subtree:true,characterData:true});const panel=status.parentElement;panel.classList.add('kb-save-inline');const header=document.querySelector('header');if(header)header.after(panel);}
   const area=document.getElementById('prosjekterInnhold');if(area){const search=document.createElement('input');search.id='kb-project-search';search.type='search';search.className='kb-search';search.placeholder='Søk etter prosjekt, kunde eller adresse';search.setAttribute('aria-label',search.placeholder);area.before(search);search.addEventListener('input',()=>setProsjektTab('liste'));}
 }
 // Existing HMS search fields stay close to each list, with accessible labels.
 for(const input of document.querySelectorAll('#sja-sok,#avvik-sok,#vr-sok,#stoff-sok')){input.type='search';input.setAttribute('aria-label',input.placeholder);}
})();
