(function(){
 'use strict';
 if(window.parent!==window)return;
 const css=document.createElement('style');css.textContent='.kb-quick{border:1px solid #dbe3ea;border-radius:12px;background:white;padding:18px;margin:20px 0}.kb-quick h3{margin:0 0 12px}.kb-quick button{padding:12px;border:1px solid #ccd8e3;border-radius:8px;background:#f4f7fa;color:#17324d;cursor:pointer;text-align:left;font:inherit}.kb-quick-list{display:flex;flex-wrap:wrap;gap:10px;margin-top:12px}.kb-quick-list button{flex:1 1 210px}.kb-quick small{display:block;margin-top:5px;color:#526779}.kb-search{display:block;width:100%;padding:12px;margin:12px 0;border:1px solid #ccd8e3;border-radius:8px;font:inherit}.kb-home{display:inline-flex;align-items:center;min-height:44px;padding:8px 12px;color:#17324d;background:#f1f5f9;border-radius:8px;text-decoration:none}.kb-save-inline{position:sticky!important;top:0;bottom:auto!important;left:auto!important;max-width:none!important;margin:10px 0!important;z-index:90!important}@media print{.kb-quick,.kb-home,.kb-save-inline{display:none!important}}';document.head.append(css);
 for(const a of document.querySelectorAll('a[href="anbudskalkulator.html"],a[href="/anbudskalkulator.html"]'))if(a.textContent.trim()==='Anbudskalkulator')a.textContent='Mine verktøy';
 if(!document.querySelector('nav a[href="anbudskalkulator.html"],nav a[href="/anbudskalkulator.html"]')&&KBAuth.can('projects')&&!document.querySelector('a[href="/anbudskalkulator.html"]')){const home=document.createElement('a');home.href='/anbudskalkulator.html';home.className='kb-home';home.textContent='← Mine verktøy';document.querySelector('main')?.prepend(home);}
 const title=document.getElementById('hovedmenyTittel');
 if(title&&typeof lasteProsjekter==='function'){
   const section=document.createElement('section');section.className='kb-quick';section.innerHTML='<h3>Fortsett med et prosjekt</h3><button type="button">+ Nytt prosjekt</button><div class="kb-quick-list"></div>';
   title.before(section);section.querySelector('button').onclick=()=>{nyttProsjekt();render();};
   const list=section.querySelector('.kb-quick-list');
   function render(){list.replaceChildren();const projects=lasteProsjekter().slice().sort((a,b)=>String(b.sist_endret||b.dato).localeCompare(String(a.sist_endret||a.dato))).slice(0,4);if(!projects.length){const p=document.createElement('p');p.textContent='Ingen lagrede prosjekter ennå. Start med «Nytt prosjekt».';list.append(p);}for(const p of projects){const b=document.createElement('button');b.type='button';const name=document.createElement('strong');name.textContent=p.navn||'Uten navn';const meta=document.createElement('small');meta.textContent=[p.kunde,'Sist endret '+new Date(p.sist_endret||p.dato).toLocaleDateString('nb-NO')].filter(Boolean).join(' · ');b.append(name,meta);b.onclick=()=>{lastInnProsjekt(p.id);switchTab(p.state?.currentTab||'start');};list.append(b);}}
   render();const status=document.getElementById('kb-save-status');if(status){new MutationObserver(render).observe(status,{childList:true,subtree:true,characterData:true});const panel=status.parentElement;panel.classList.add('kb-save-inline');const header=document.querySelector('header');if(header)header.after(panel);}
   const area=document.getElementById('prosjekterInnhold');if(area){const search=document.createElement('input');search.id='kb-project-search';search.type='search';search.className='kb-search';search.placeholder='Søk etter prosjekt, kunde eller adresse';search.setAttribute('aria-label',search.placeholder);area.before(search);search.addEventListener('input',()=>setProsjektTab('liste'));}
 }
 // Existing HMS search fields stay close to each list, with accessible labels.
 for(const input of document.querySelectorAll('#sja-sok,#avvik-sok,#vr-sok,#stoff-sok')){input.type='search';input.setAttribute('aria-label',input.placeholder);}
})();
