(function(){
'use strict';if(!KBAuth.can('projects'))return;
const form=document.getElementById('offer-form'),status=document.getElementById('offer-status'),preview=document.getElementById('offer-preview'),letter=document.getElementById('print-letter');let dirty=false;
const $=id=>document.getElementById(id),value=id=>$(id).value.trim();
const format=cents=>new Intl.NumberFormat('nb-NO',{style:'currency',currency:'NOK'}).format(cents/100);
const day=d=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
const dateLabel=s=>new Date(s+'T12:00:00').toLocaleDateString('nb-NO');
const now=new Date(),expiry=new Date(now);expiry.setDate(expiry.getDate()+30);$('date').value=day(now);$('valid').value=day(expiry);
for(const id of ['labour','materials','other'])$(id).value='0';
$('sender-name').textContent=KBAuth.employee.name;$('sender-email').textContent=KBAuth.employee.email;
function amounts(){const a=['labour','materials','other'].map(id=>Math.round(Number(value(id))*100));const net=a.reduce((sum,n)=>sum+n,0),vat=Math.round(net*.25);return {a,net,vat,total:net+vat};}
function node(tag,text){const el=document.createElement(tag);el.textContent=text;return el;}
function totals(){const a=amounts();$('totals').replaceChildren(...[['Sum eks. MVA',a.net],['MVA 25 %',a.vat],['Totalt inkl. MVA',a.total]].map(([label,n])=>{const p=node('p','');p.append(node('span',label),node('strong',format(n)));return p;}));}
function data(){const a=amounts();return {title:value('title'),reference:value('reference'),dateLabel:dateLabel(value('date')),validLabel:dateLabel(value('valid')),customer:value('customer'),email:value('email'),address:value('address'),intro:value('intro'),work:value('work'),terms:value('terms'),schedule:value('schedule'),payment:value('payment'),phone:value('phone'),priceType:value('price-type'),senderName:KBAuth.employee.name,senderEmail:KBAuth.employee.email,rows:[...['Arbeid eks. MVA','Materialer eks. MVA','Frakt og annet eks. MVA'].map((label,i)=>({label,value:format(a.a[i])})),{label:'Sum eks. MVA',value:format(a.net)},{label:'MVA 25 %',value:format(a.vat)},{label:'Totalt inkl. MVA',value:format(a.total),total:true}]};}
function valid(){status.textContent='';if(!form.reportValidity())return false;if(!value('work')){status.textContent='Beskriv arbeidet som inngår i tilbudet.';$('work').focus();return false;}if(amounts().net<=0){status.textContent='Tilbudet har 0 kr i pris. Fyll inn prisen før du lager PDF.';$('labour').focus();return false;}if(value('valid')<value('date')){status.textContent='Gyldighetsdato må være på eller etter tilbudsdato.';$('valid').focus();return false;}return true;}
function render(d){const fragment=document.createDocumentFragment();const brand=node('div','KOMPLETT BYGGDRIFT AS · TILBUDSBREV');brand.className='letter-brand';fragment.append(brand,node('h1',d.title),node('p','Tilbudsreferanse: '+d.reference+' · '+d.dateLabel));for(const [title,body] of [['Kunde og prosjekt',d.customer+(d.email?'\n'+d.email:'')+'\n'+d.address],['Innledning',d.intro],['Arbeid som inngår',d.work]]){if(body)fragment.append(node('h2',title),node('p',body));}fragment.append(node('h2','Pris – '+d.priceType));const table=node('table','');for(const row of d.rows){const tr=node('tr','');tr.append(node('td',row.label),node('td',row.value));table.append(tr);}fragment.append(table);for(const [title,body] of [['Forbehold og avgrensninger',d.terms],['Fremdrift',d.schedule],['Betalingsbetingelser',d.payment]])if(body)fragment.append(node('h2',title),node('p',body));fragment.append(node('p','Tilbudet gjelder til '+d.validLabel+'.'),node('p','For Komplett Byggdrift AS\n'+d.senderName+'\n'+d.senderEmail+' · '+d.phone));const footer=node('p','Komplett Byggdrift AS · Org.nr. 926 335 758 MVA\nkomplettbyggdrift.no');footer.className='company';fragment.append(footer);letter.replaceChildren(fragment);}
form.addEventListener('submit',e=>e.preventDefault());form.addEventListener('input',()=>{dirty=true;preview.hidden=true;totals();});
$('preview').addEventListener('click',()=>{if(!valid())return;render(data());preview.hidden=false;preview.scrollIntoView({behavior:'smooth'});});
$('edit').addEventListener('click',()=>{preview.hidden=true;form.scrollIntoView({behavior:'smooth'});});
$('pdf').addEventListener('click',async()=>{if(!valid())return;const button=$('pdf');button.disabled=true;try{const d=data();const pdf=KBOfferPDF.create(d,jspdf.jsPDF);const filename=('Tilbud-'+d.reference).replace(/[^a-zA-Z0-9ÆØÅæøå_-]/g,'-').slice(0,100)+'.pdf';await pdf.save(filename,{returnPromise:true});dirty=false;status.textContent='PDF-en er klargjort for nedlasting. Legg den ved e-posten du sender til kunden.';}catch{status.textContent='PDF-en kunne ikke lages. Prøv igjen eller last siden på nytt etter at du har kopiert teksten din.';}finally{button.disabled=false;}});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});totals();
})();
